name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - 'HalfFifty_BE/**'
  pull_request:
    paths:
      - 'HalfFifty_BE/**'

jobs:
  # 1. 테스트 및 빌드
  test:
    name: Test and Build Backend
    runs-on: ubuntu-latest

    steps:

      # 1.1 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 1.2 JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add execute permissions to Gradlew
        run: chmod +x ./gradlew
        working-directory: HalfFifty_BE

      # Gradle 빌드 및 테스트
      - name: Build and Test
        working-directory: HalfFifty_BE
        env:
          DB_DRIVER_CLASS_NAME: ${{ secrets.DB_DRIVER_CLASS_NAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ./gradlew clean build

  deploy:
    name: Deploy Backend
    needs: test  # 빌드/테스트가 성공해야 실행
    if: github.ref == 'refs/heads/main'   # main 브랜치에서만 실행
    runs-on: ubuntu-latest

    steps:
      # 2.1 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2.2 JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2.3 빌드된 JAR 파일을 EC2로 전송
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          source: ./HalfFifty_BE/build/libs/HalfFifty_BE-0.0.1-SNAPSHOT.jar
          target: ~/HalfFifty_BE-0.0.1-SNAPSHOT.jar

      # 2.4 EC2에서 Docker Compose로 배포 실행
      - name: Deploy to EC2 using Docker Compose
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~
            docker-compose down || true
            docker-compose up -d --build
