name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - 'HalfFifty_BE/**'
  pull_request:
    paths:
      - 'HalfFifty_BE/**'

jobs:
  test:
    name: Test and Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add execute permissions to Gradlew
        run: chmod +x ./gradlew
        working-directory: HalfFifty_BE

      # Gradle 빌드 및 테스트
      - name: Build and Test
        working-directory: HalfFifty_BE
        env:
          DB_DRIVER_CLASS_NAME: ${{ secrets.DB_DRIVER_CLASS_NAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ./gradlew clean build

  deploy:
    name: Deploy Backend
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker Image
        working-directory: HalfFifty_BE
        run: docker build -t half-fifty:latest .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker stop half-fifty || true
            docker rm half-fifty || true
            docker run -d -p 80:8080 --name half-fifty half-fifty:latest

      - name: Verify Container Status
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: docker ps | grep half-fifty
